package mx.astro.simulation.application;

import mx.astro.simulation.domain.JobReport;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

/**
 * Renders a {@link JobReport} into a self-contained LaTeX source ready for
 * pdflatex (or upload to Overleaf). Plot PNGs must already exist in the same
 * directory — this class only writes {@code report.tex}.
 *
 * <p>Style: AAS journal-ish layout, single-column. Avoids package dependencies
 * other than {@code graphicx} and {@code booktabs} so it compiles with a bare
 * texlive install.
 */
@Component
public class LatexReportRenderer {

    private static final Logger log = LoggerFactory.getLogger(LatexReportRenderer.class);

    /**
     * Write {@code report.tex} into {@code outDir}. The file references plot
     * images by relative name ({@code energy.png}, etc.) — they are only
     * embedded if the corresponding files exist next to the .tex.
     */
    public Path render(JobReport report, Path outDir) throws IOException {
        Files.createDirectories(outDir);
        Path texPath = outDir.resolve("report.tex");

        StringBuilder sb = new StringBuilder(8192);
        sb.append("""
                \\documentclass[11pt,a4paper]{article}
                \\usepackage[margin=2.2cm]{geometry}
                \\usepackage{graphicx}
                \\usepackage{booktabs}
                \\usepackage{siunitx}
                \\usepackage{hyperref}
                \\hypersetup{colorlinks=true, urlcolor=blue!50!black, linkcolor=black}
                \\title{N-body simulation report \\\\ \\large scenario \\texttt{%s}}
                \\author{astro N-body workbench}
                \\date{Job %s}

                \\begin{document}
                \\maketitle

                \\section*{Run parameters}
                \\begin{tabular}{ll}
                  \\toprule
                  Scenario        & \\texttt{%s} \\\\
                  Bodies (N)      & %d \\\\
                  Integrator step & $\\Delta t = %s$ \\\\
                  Softening       & $\\varepsilon = %s$ \\\\
                  Total steps     & %d \\\\
                  Random seed     & %d \\\\
                  Snapshots       & %d \\\\
                  \\bottomrule
                \\end{tabular}

                """.formatted(
                escape(report.scenario()),
                escape(report.jobId()),
                escape(report.scenario()),
                report.nBodies(),
                fmt(report.dt()),
                fmt(report.softening()),
                report.nSteps(),
                report.seed(),
                report.timeline().size()
        ));

        sb.append("\\section*{Conservation diagnostics}\n");
        sb.append("\\begin{tabular}{lr}\n  \\toprule\n");
        sb.append("  Quantity & Value \\\\\n  \\midrule\n");
        for (var e : report.conservation().entrySet()) {
            sb.append("  ").append(latexLabel(e.getKey()))
              .append(" & ").append(fmtSci(e.getValue())).append(" \\\\\n");
        }
        sb.append("  \\bottomrule\n\\end{tabular}\n\n");

        // Embed plots only if they exist — keeps the report compilable even
        // if plot generation partially failed.
        embedFigure(sb, outDir, "energy.png", "Energy timeline.");
        embedFigure(sb, outDir, "virial.png", "Virial ratio: oscillations near $Q=1$ indicate a relaxed system.");
        embedFigure(sb, outDir, "lagrangian.png",
                "Lagrangian radii — divergence between $r_{10}$ and $r_{90}$ tracks core collapse and halo expansion.");
        embedFigure(sb, outDir, "binaries.png",
                "Bound pair detection. Tightest hard binaries should harden over time (Heggie 1975).");
        embedFigure(sb, outDir, "escapers.png", "Cumulative escaper timeline.");

        // Top-K hard binaries table.
        appendBinariesTable(sb, report);
        appendEscapersTable(sb, report);

        sb.append("""

                \\section*{Reproducibility}
                This report was generated by the astro N-body workbench from the multi-snapshot
                HDF5 file written during the run. All physical quantities are in
                Hénon units ($G = M = -4E = 1$). The integration used a leapfrog
                scheme with Plummer softening; reported energies include the same
                softening for self-consistency with the dynamics.

                \\end{document}
                """);

        Files.writeString(texPath, sb.toString());
        log.info("Wrote LaTeX report to {}", texPath);
        return texPath;
    }

    // ============================================================
    // helpers
    // ============================================================

    private static void embedFigure(StringBuilder sb, Path outDir, String filename, String caption) {
        Path img = outDir.resolve(filename);
        if (!Files.exists(img)) return;
        sb.append("\\begin{figure}[htbp]\n  \\centering\n");
        sb.append("  \\includegraphics[width=\\linewidth]{").append(filename).append("}\n");
        sb.append("  \\caption{").append(caption).append("}\n\\end{figure}\n\n");
    }

    private static void appendBinariesTable(StringBuilder sb, JobReport report) {
        List<JobReport.BinaryEvent> bins = report.binaries();
        if (bins.isEmpty()) {
            sb.append("\\section*{Binary catalog}\nNo bound pairs detected during the run.\n\n");
            return;
        }
        List<JobReport.BinaryEvent> top = bins.stream()
                .sorted((a, b) -> Double.compare(a.separation(), b.separation()))
                .limit(10).toList();
        int total = bins.size();
        long hardCount = bins.stream().filter(JobReport.BinaryEvent::hard).count();
        sb.append("\\section*{Binary catalog}\n");
        sb.append("Detected ").append(total).append(" bound-pair events across all snapshots, ");
        sb.append("of which ").append(hardCount).append(" are \\emph{hard} ($|E_{\\rm pair}| > kT$). ");
        sb.append("Top-").append(top.size()).append(" tightest pairs:\n\n");
        sb.append("\\begin{tabular}{rrrrrrrc}\n  \\toprule\n");
        sb.append("  $t$ & step & A & B & $r$ & $a$ & $e$ & hard \\\\\n  \\midrule\n");
        for (var b : top) {
            sb.append(String.format(Locale.ROOT,
                    "  %.3f & %d & %d & %d & %s & %s & %.3f & %s \\\\\n",
                    b.simTime(), b.stepIndex(), b.bodyA(), b.bodyB(),
                    fmtSci(b.separation()), fmtSci(b.semiMajorAxis()), b.eccentricity(),
                    b.hard() ? "Y" : "N"));
        }
        sb.append("  \\bottomrule\n\\end{tabular}\n\n");
    }

    private static void appendEscapersTable(StringBuilder sb, JobReport report) {
        List<JobReport.EscaperEvent> esc = report.escapers();
        sb.append("\\section*{Escaper catalog}\n");
        if (esc.isEmpty()) {
            sb.append("No bodies escaped the cluster during the run.\n\n");
            return;
        }
        // Show first 10 escapers (chronological).
        sb.append("Total: ").append(esc.size()).append(" bodies became unbound. First 10:\n\n");
        sb.append("\\begin{tabular}{rrrrr}\n  \\toprule\n");
        sb.append("  body & escape $t$ & step & $r$ & $|v|$ \\\\\n  \\midrule\n");
        esc.stream().limit(10).forEach(e -> sb.append(String.format(Locale.ROOT,
                "  %d & %.3f & %d & %s & %s \\\\\n",
                e.bodyIndex(), e.escapeTime(), e.escapeStepIndex(),
                fmtSci(e.escapeRadius()), fmtSci(e.escapeSpeed()))));
        sb.append("  \\bottomrule\n\\end{tabular}\n\n");
    }

    private static String fmt(double v)        { return String.format(Locale.ROOT, "%.4g", v); }
    private static String fmtSci(double v)     { return String.format(Locale.ROOT, "%.3e", v); }

    /** Map the JSON conservation key to a LaTeX-friendly label. */
    private static String latexLabel(String key) {
        return switch (key) {
            case "dE_over_E_initial"    -> "$|\\Delta E / E_0|$ (final)";
            case "dL_over_L_initial"    -> "$|\\Delta L / L_0|$ (final)";
            case "worst_dE_over_E"      -> "$|\\Delta E / E_0|$ (worst)";
            default -> escape(key);
        };
    }

    /** Minimal LaTeX escaping for user-supplied strings (scenario name, UUID). */
    private static String escape(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\")
                .replace("_", "\\_")
                .replace("&", "\\&")
                .replace("%", "\\%")
                .replace("$", "\\$");
    }
}
